#!/bin/bash

# Record the SPIRV-Cross revision as a derived header file suitable for including in a build
EXT_DIR="${SRCROOT}/External"
EXT_REV_DIR="${SRCROOT}/ExternalRevisions"
REPO_NAME=SPIRV-Cross
REPO_REV=$(cat "${EXT_REV_DIR}/${REPO_NAME}_repo_revision")
HDR_FILE=${EXT_DIR}/${REPO_NAME}/mvkSpirvCrossRevisionDerived.h
echo "// Auto-generated by MoltenVK" > "${HDR_FILE}"
echo "static const char* spirvCrossRevisionString = \"${REPO_REV}\";" >> "${HDR_FILE}"

