#!/bin/bash
#
# Copyright (c) 2016-2020 The Brenwill Workshop Ltd.
#
# generateSPIRVShaders - Convert GLSL shader files to SPIRV header files
#
# macOS usage: ./generateSPIRVShaders
#

set -e

echo
echo ========== Converting API-Samples shader files ==========
echo

cd "../../.."

"Package/Latest/MoltenVKShaderConverter/Tools/MoltenVKShaderConverter"  \
 -r -gi -so -oh -xs . -q  \
 -d "Demos/LunarG-VulkanSamples/VulkanSamples/API-Samples" > /dev/null

cd -  > /dev/null

echo ========== Done! ==========

